const expo = require('eslint-config-expo/flat');

module.exports = [
  ...expo,
  {
    // Generated by drizzle-kit and committed; not ours to lint.
    ignores: ['drizzle/**', '.expo/**', 'dist/**', 'expo-env.d.ts'],
  },
  {
    rules: {
      // The design tokens are the only place a colour literal belongs, and the
      // schema is deliberately comment-heavy. Nothing else to relax yet.
    },
  },
];
